name: PerfectCosmetics
version: '1.0-SNAPSHOT'
main: org.aneras.mc.perfectcosmetics.PerfectCosmetics
api-version: 1.16
authors: [ Aneras ]
commands:
  perfectCosmetics:
    usage:
      -/perfectcosmetics head/body/offhand